# Generated by Django 4.2.7 on 2023-11-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanApplicatin',
            new_name='LoanApplication',
        ),
    ]
