# Generated by Django 4.2.7 on 2023-11-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanInsRegister',
            new_name='LoanInsRegister2',
        ),
    ]
