# Generated by Django 4.2.7 on 2023-11-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_loaninsregister_loaninsregister2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanInsRegister2',
            new_name='LoanInsRegisterAPI',
        ),
    ]
