# Generated by Django 4.2.7 on 2023-11-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_loaninsregister2_loaninsregisterapi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanRegister',
            new_name='LoanRegisterAPI',
        ),
    ]
